
const payments = [
    {
        method: 'WechatPay',
        logo: 'Wallet/WechatPay/WeChat_V1_ROU.svg',
        region: 'China',
        systemMethod: 'WECHATPAY',
        quickPay: true,
        web: true,
        mobileWeb: false,
        transactionQR: true,
    },
    {
        method: 'WechatPay',
        logo: 'Wallet/WechatPay/WeChat_V1_ROU.svg',
        region: 'Malaysia',
        systemMethod: 'WECHATPAY',
        quickPay: true,
        web: true,
        mobileWeb: false,
        transactionQR: true,
    },
    {
        method: 'Presto',
        logo: 'Wallet/Presto/Presto_V1_ROU.svg',
        region: 'Malaysia',
        systemMethod: 'PRESTO',
        quickPay: true,
        web: true,
        mobileWeb: true,
        transactionQR: true,
    },
    {
        method: 'Alipay',
        logo: 'Wallet/Alipay/Alipay_V1_ROU.svg',
        region: 'China',
        systemMethod: 'ALIPAY',
        quickPay: true,
        web: true,
        mobileWeb: true,
        transactionQR: true,
    },
    {
        method: 'TNG',
        logo: 'Wallet/TNG/TNG_V1_ROU.svg',
        region: 'Malaysia',
        systemMethod: 'TNG',
        quickPay: true,
        web: true,
        mobileWeb: true,
    },
    {
        method: 'Boost',
        logo: 'Wallet/Boost/Boost_V1_ROU.svg',
        region: 'Malaysia',
        systemMethod: 'BOOST',
        quickPay: true,
        web: true,
        mobileWeb: true,
        transactionQR: true,
    },
    {
        method: 'Maybank',
        logo: 'Banks/Maybank/MayBank_V1_ROU.svg',
        region: 'Malaysia',
        systemMethod: 'MAYBANK',
        quickPay: true,
        web: true,
    },
    {
        method: 'GrabPay',
        logo: 'Wallet/GrabPay/GrabPay_V1_ROU.svg',
        region: 'Malaysia',
        systemMethod: 'GRABPAY',
        quickPay: true,
        web: true,
        mobileWeb: true,
    },
    {
        method: 'ShopeePay',
        logo: 'Wallet/ShopeePay/ShopeePay_V1_ROU.svg',
        region: 'Malaysia',
        systemMethod: 'SHOPEEPAY',
        quickPay: true,
        web: true,
        mobileWeb: true,
    },
    {
        method: 'Gobiz',
        logo: 'Card/Gobiz/Gobiz_V1_ROU.svg',
        region: 'Malaysia',
        systemMethod: 'GOBIZ',
        web: true,
        mobileWeb: true,
    },
    {
        method: 'Paydee',
        logo: 'Card/Paydee/Paydee_V1_ROU.svg',
        region: 'Malaysia',
        systemMethod: 'PAYDEE',
        web: true,
        mobileWeb: true,
    },
    {
        method: 'Zapp',
        logo: 'Wallet/Zapp/Zapp_V1_ROU.svg',
        region: 'Malaysia',
        systemMethod: 'ZAPP',
        quickPay: true,
        mobileWeb: true,
    },
    {
        method: 'Tapay',
        logo: 'Wallet/TaPay/TaPay_V1_ROU.svg',
        region: 'Malaysia',
        systemMethod: 'TAPAY',
        quickPay: true,
    },
    {
        method: 'MCash',
        logo: 'Wallet/MCash/MCash_V1_ROU.svg',
        region: 'Malaysia',
        systemMethod: 'MCASH',
        quickPay: true,
        web: true,
        mobileWeb: true,
    },
    {
        method: 'Lazada',
        logo: 'Wallet/Lazada/Lazada_V1_ROU.svg',
        region: 'Malaysia',
        systemMethod: 'LAZADA',
        quickPay: true,
    },
    {
        method: 'FPX',
        logo: 'Other/FPX/FPX_V1_ROU.svg',
        region: 'Malaysia',
        systemMethod: 'FPX',
        web: true,
        mobileWeb: true,
    },
    {
        method: 'SarawakPay',
        logo: 'Wallet/SarawakPay/SarawakPay_V1_ROU.svg',
        region: 'Malaysia',
        systemMethod: 'SARAWAKPAY',
        quickPay: true,
        web: true,
        mobileWeb: true,
    },
    {
        method: 'FavePay',
        logo: 'Wallet/FavePay/FavePay_V1_ROU.svg',
        region: 'Malaysia',
        systemMethod: 'FAVEPAY',
        quickPay: true,
        web: true,
    },
    {
        method: 'BInfinite',
        logo: 'Wallet/Binfinite/Binfinite_V1_ROU.svg',
        region: 'Malaysia',
        systemMethod: 'BINFINITE',
        quickPay: true,
        web: true,
    },
    {
        method: 'Alipay+',
        logo: 'Wallet/AlipayPlus/AlipayPlus_V1_ROU.svg',
        region: 'Malaysia',
        systemMethod: 'ALIPAYPLUS',
        quickPay: true,
        web: true,
        mobileWeb: true,
    },
    {
        method: 'SenHengPay',
        logo: 'Wallet/Senheng/Senheng_V1_ROU.svg',
        region: 'Malaysia',
        systemMethod: 'SENHENGPAY',
        web: true,
        mobileWeb: true,
    },
    {
        method: 'Split',
        logo: 'BNPL/Split/Split_V1_ROU.svg',
        region: 'Malaysia',
        systemMethod: 'SPLIT',
        web: true,
    },
    {
        method: 'IOUPay',
        logo: 'BNPL/IOUPay/IOUPay_V1_ROU.svg',
        region: 'Malaysia',
        systemMethod: 'IOUPAY',
        web: true,
    },
    {
        method: 'Atome',
        logo: 'BNPL/Atome/Atome_V1_ROU.svg',
        region: 'Malaysia',
        systemMethod: 'ATOME',
        quickPay: true,
        web: true,
    },
    {
        method: 'NetsPay',
        logo: 'Other/NetsPay/NetsPay_V1_ROU.svg',
        region: 'Singapore',
        systemMethod: 'NETSPAY',
        web: true,
        retailQR: true,
    },
    {
        method: 'Setel',
        logo: 'Wallet/Setel/Setel_V1_ROU.svg',
        region: 'Malaysia',
        systemMethod: 'SETEL',
        quickPay: true,
        web: true,
    },
];

export default payments;
